// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: review.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const addReview = `-- name: AddReview :exec
INSERT INTO reviews (flashcard_id, user_id, remembered, reviewed_at)
VALUES ($1, $2, $3, NOW())
`

type AddReviewParams struct {
	FlashcardID uuid.UUID `json:"flashcard_id"`
	UserID      uuid.UUID `json:"user_id"`
	Remembered  bool      `json:"remembered"`
}

func (q *Queries) AddReview(ctx context.Context, arg AddReviewParams) error {
	_, err := q.db.Exec(ctx, addReview, arg.FlashcardID, arg.UserID, arg.Remembered)
	return err
}
